### ISSUE TITLE
📌 SPIKE: Have one EKS cluster with multiple namespaces for workloads

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#104]
Timebox: 1 day

## User Story

As a CloudOps Engineer
I want to have one Elastic Kubernetes cluster
So that the management and cost of our services are reduced.

## Value / Purpose

We have 3 x EKS main clusters in our accounts plus some named individuals.
We are only running our IMA workloads currently.
We could do with consolidating onto production and using namespaces for testing 
We can keep using Development for upgrades but need to ensure that resources are destroyed when not in use.
- 💰 Cost
- 😌 Administration

## Additional Information
We should be thinking about how to align with Cloud Platform once CIDR conflicts are resolved [see here](https://github.com/ministryofjustice/cloud-operations/blob/main/architecture-decision-record/007-use-prometheus-and-grafana-for-metrics-alerting.md#:~:text=Update%207th%20January%202022%20The%20IMA%20infrastructure%20can%20be%20moved%20to%20Cloud%20Platform%2C%20but%20requires%20the%20following%20issue%20(see%20issue%20here)%20resolved.)

- Investigate GitOps model e.g. [ArgoCD](https://aws.amazon.com/blogs/containers/gitops-model-for-provisioning-and-bootstrapping-amazon-eks-clusters-using-crossplane-and-flux/)/Flux (Kubectl applier) to remove the need for CodePipelines and further reduce our complexity.
- Using [Sealed Secrets](https://aws.amazon.com/blogs/opensource/managing-secrets-deployment-in-kubernetes-using-sealed-secrets/) to version our secrets and further automate our deployments.

## Definition of Done (DoD)

Have discussed as a team, issues raised on our backlog.

Checklist for definition of done and acceptance criteria, example below (optional).

- [ ] Lightning talk/demo on any proposed changes to the architecture 
- [ ] GitHub Issues raised

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by mTouhid** [comment]
## Outcome:
 - IMA terraform to not create EKS clusters in non-production environments 
 - Production EKS Cluster to host development and pre-production namespaces together with production namespace
 - Grafana to be migrated into a pod in the prod EKS cluster
 - Consolidate EKS configmaps templates into deployment yaml templates repository.

**Comment by mTouhid** [comment]
4 relevant GitHub issues have been created.
