### ISSUE TITLE
✨ Add GitHub Action Link Checker to our team repo

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#106]
## User Story

As a Cloud Ops engineer
I want to know if the links in our documentation are valid
So that our documentation is current

## Value / Purpose

Automatically check links in our [Cloud Operations](https://github.com/ministryofjustice/cloud-operations) repository are valid.
Automatically create GitHub Issues when dead links are found.

## Useful Contacts

RB

## Additional Information

[lychee link checking action](https://github.com/lycheeverse/lychee-action)

![image.png](https://images.zenhubusercontent.com/5ee0e1070c1bdefe59b421df/5734b2a9-cd7c-4134-a965-53aefd71c59e)

See example CP issue [here](https://github.com/ministryofjustice/cloud-platform/issues/3725)
## Definition of Done (DoD)

Action is scheduled to run nightly
Issues are raised automatically

Checklist for definition of done and acceptance criteria, example below (optional).

- [ ] README has been updated 
- [ ] Another team member has reviewed  
- [ ] Tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/cloud-operations/106?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson
