### ISSUE TITLE
🧱 Terraform Module Dependabots

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/cloud-operations#108]
## User Story

As a… cloud ops engineer
I need/want/expect to… a dependabot issue to be opened when a module in terraform can be updated
So that… we keep our modules up to date.

## Value / Purpose

This will automate the update of these modules and stop us having to update multiple things at once when upgrading terraform.

## Definition of Done (DoD)

Completed for the following: 
- [x] [staff-infrastructure-monitoring-config](https://github.com/ministryofjustice/staff-infrastructure-monitoring-config) 
- [x] [staff-device-dns-dhcp-infrastructure](https://github.com/ministryofjustice/staff-device-dns-dhcp-infrastructure)
- [x] [staff-device-shared-services-infrastructure](https://github.com/ministryofjustice/staff-device-shared-services-infrastructure)

**Comment by ASTRobinson** [comment]
Renovate now rolled out to the below repos:
      'ministryofjustice/cloud-operations-github-actions',
      'ministryofjustice/staff-infrastructure-monitoring',
      'ministryofjustice/staff-infrastructure-monitoring-config',
      'ministryofjustice/staff-device-dns-dhcp-infrastructure',
      'ministryofjustice/staff-device-shared-services-infrastructure',

**Comment by ASTRobinson** [comment]
Renovate now successfully deployed and creating PR for terraform 
https://github.com/renovatebot/renovate#readme
