### ISSUE TITLE
🔐 Enroll AWS Shield Advanced on Pre Production

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#113]
As per this [issue](https://github.com/ministryofjustice/cloud-operations/issues/77)
Enroll Pre-Production with PR [here](https://github.com/ministryofjustice/aws-root-account/blob/main/organisation-security/terraform/locals.tf)

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/cloud-operations/113?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson

**Comment by bagg3rs** [comment]
https://github.com/ministryofjustice/aws-root-account/pull/485
