### ISSUE TITLE
🔐 Enrol AWS Shield Advanced on Production

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#114]
As per this [issue](https://github.com/ministryofjustice/cloud-operations/issues/77)
Enroll Production with PR [here](https://github.com/ministryofjustice/aws-root-account/blob/main/organisation-security/terraform/locals.tf)

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/cloud-operations/114?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson

**Comment by jakemulley** [comment]
All Technology Services AWS accounts are now enrolled into the non-auto-remediate policy through ministryofjustice/aws-root-account#519.

To make the most of Shield Advanced, in the future we'll need to move this to the auto-remediate policy, which adds empty WAFs for to resources for monitoring DDoS events.

Further, the Modernisation Platform team have put together a user guide on next steps when Enabling [AWS Shield Advanced](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/enabling-shield-advanced.html#enabling-aws-shield-advanced-for-production-applications) for production applications.

**Comment by bagg3rs** [comment]
We can use this for the alert 
https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/performance-hub/monitoring.tf#L3

**Comment by bagg3rs** [comment]
We do not have a repo for defining alerts have created an [issue](https://github.com/ministryofjustice/cloud-operations/issues/193) to address this and also we have a spike to look to alert pagerduty which would tie this all together.
