### ISSUE TITLE
📌 SPIKE: Use AWS Graviton for workloads

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#115]
Timebox .5 day
## User Story

As a CloudOps engineer
I want to practice sustainability 
So that we can reduce our cloud spend and follow [TCOP guidance point 12.](https://www.gov.uk/guidance/make-your-technology-sustainable)

## Value / Purpose

🌱  less power #sustainability
💰  lower cost
🚀  better performance
Discussing with AWS there seems to be very little effort to switch e.g. RDS instances.

## Useful Contacts

RB

## Additional Information

[AWS services supporting Graviton](https://aws.amazon.com/ec2/graviton/)
[Key considerations in moving to Graviton2 for Amazon RDS and Amazon Aurora databases](https://aws.amazon.com/blogs/database/key-considerations-in-moving-to-graviton2-for-amazon-rds-and-amazon-aurora-databases/)

## Definition of Done (DoD)

Discussed as team
Issues raised 

Checklist for definition of done and acceptance criteria, example below (optional).

- [ ] Documentation has been written / updated  
- [ ] Issues raised
- [ ] Add to show and tell

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by Gary-H9** [comment]
The team completed this spike this morning. 

The work following this can be split up into three main components:
- Upgrading AWS RDS Databases to utilise AWS Graviton instances. 
- Upgrading Containers to be able to use ARM processors. (this is a pre-requisite to the next ticket)
- Upgrade AWS ECS/EKS to utilise AWS Graviton instances.

### Cost Comparison 

| Instance      | Cost (per month) | CPU | RAM (GiB) |
|---------------|------------------|-----|-----------|
| `t2.large`      | ~$232            | 2   | 8         |
| `t4g.large`     | ~$219            | 2   | 8         |
| `db.t2.medium`  | ~$119            | 2   | 8         |
| `db.t4g.medium` | ~$34             | 2   | 8         |
| `t3.medium`     | ~$37             | 2   | 4         |
| `t4g.medium`    | ~$34             | 2   | 4         |

Instances which use Row 2 would replace Row 1. This applies for Rows 4 and 3, as well as 6 and 5. 

Rows 1-4 represent RDS instances which would change type. 
Rows 5-6 will be the changes made for our EKS and ECS workloads.

Monthly cost from [here](https://calculator.aws/#/createCalculator/EC2 ) and [here](https://calculator.aws/#/createCalculator/RDSMySQL). 
___________________________________________________________

It should be discussed if the ECS / EKS change is worth the effort. 
$3 difference per month => 3 instances x 3 => $118 dollar saving a year, to improve the compute (which we don't have any issues with currently). Long term this cluster will only exist in prod so I've not included Dev and Pre-Prod in this calculation.
