### ISSUE TITLE
📌  SPIKE: Use PagerDuty to integrate and route our alerts

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#122]
Timebox 1 day? 🤔

## User Story

As a CloudOps Engineer
I want to simplify alerting integration with other services
So that we don't need to manage systems to convert AlertManager messages to ServiceNow

## Value / Purpose

By using PagerDuty
- Remove the need to maintain and develop integration between primarily Prometheus AlertManager and ServiceNow (no native integration)
- Remove alert logic from AlertManager
- Standardise with other MoJ Teams including Cloud and Modernisation Platform (we can re-use their code)
- Gain on-call rota and much more

## Useful Contacts

Rich/Dan Sablu from Cloud Platform [Operations Enginering](https://operations-engineering.service.justice.gov.uk/documentation/services.html)

## Additional Information

https://www.pagerduty.com/integrations/

## Definition of Done (DoD)

*[Please clearly and concisely detail the DoD]*

Checklist for definition of done and acceptance criteria, example below (optional).

- [ ] Requested PagerDuty account from OpsEng
- [ ] Demo to team  
- [ ] Any additional issues raise 
- [ ] Our docs updated
- [ ] Another team member has reviewed  

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by wanieldilson** [comment]
Spike complete, Issues #195 and #196 opened.
