### ISSUE TITLE
⏩ Automatically add GitHub issues to Github Project

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#129]
## User Story

As MoJ Staff 
I want to be able to see what Cloud Operations are working on
So that I can see all the great work they are doing

## Value / Purpose

Add issues to public GitHub Project Board to allow wider teams and management to see what we are working on
Allow us to keep 👀  on [GH project boards beta](https://github.blog/changelog/label/issues/) as they are adding features quite rapidly and we could one day easily move over. 

## Useful Contacts

RB

## Additional Information

👀  see [GitHub Action by MP](https://github.com/ministryofjustice/modernisation-platform/blob/main/.github/workflows/add-issues-to-project.yml)
Our [GitHub Project board](https://github.com/orgs/ministryofjustice/projects/11/views/1)

## Definition of Done (DoD)

All issues are automatically added to GitHub Projects board.

**Comment by bagg3rs** [comment]
There is a beta Action here

https://github.com/marketplace/actions/add-to-github-projects-beta

**Comment by wanieldilson** [comment]
Added and tested for ministryofjustice/cloud-operations - Hoping to create an org-wide secret to allow us to implement on all repos easily.

**Comment by bagg3rs** [comment]
Great success
![image.png](https://images.zenhubusercontent.com/5ee0e1070c1bdefe59b421df/f459d43c-8c35-4794-9768-9afb8a5ea7ed)

**Comment by bagg3rs** [comment]
Org Secret now created
`TECH_SERVICES_GITHUB_TOKEN`

**Comment by bagg3rs** [comment]
Workflows for GitHub Projects https://github.com/orgs/ministryofjustice/projects/11/workflows/23201 changed so items added go into the backlog
![image.png](https://images.zenhubusercontent.com/5ee0e1070c1bdefe59b421df/3d62be8e-a244-4e66-90e1-88e5bcc7de0e)
