### ISSUE TITLE
💰  Enable auto scaling on Table capacity for all DynamoDB tables

### ISSUE THREAD

**Issue by mTouhid** [ministryofjustice/cloud-operations#141]
### User Story

As a… member of the CloudOps team
I want to… optimise the cost of the running DynamoDB tables for all the CI pipelines
So that… it reduces the running cost of the CI pipelines

### Value / Purpose

It reduces cost and improves scalability.

### Useful Contacts

Touhidul Islam

### Additional Information

Here is a list of tables:  

- [ ] "mojo-bootstrap-nac-infrastructure-terraform-remote-state-lock-dynamo",
- [ ] "mojo-ci-staff-external-dynamic-list-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-admin-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-aggregation-client--tf-lock-table",
- [ ] "pttp-ci-infrastructure-bb-ex-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-dns-dhcp-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-dns-server-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-ds-config-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-ima-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-ima-deploy-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-kea-server-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-log-syslog-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-nac-admin-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-nac-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-nac-server-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-net-svcs-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-pvt-dns-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-smtp-relay-client-core-tf-lock-table",
- [ ] "pttp-ci-infrastructure-snmp-client-core-tf-lock-table",
- [ ] "pttp-global-bootstrap-pttp-infrastructure-terrafrom-remote-state-lock-dynamo",
- [ ] "staff-device-ci-private-dns-zone-core-tf-lock-table",
- [ ] "tf-state-lock-dynamo-r3ih3jus"

### Definition of Done

- [ ] Change in done in code in repo [staff-device-shared-services-infrastructure](https://github.com/ministryofjustice/staff-device-shared-services-infrastructure)
- [ ] User docs have been updated, if applicable
- [ ] Another team member has reviewed
- [ ] Check if the capacities have changed using the AWS web console.

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/cloud-operations/141?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson
