### ISSUE TITLE
⏩  Automatically add and close GitHub Issues in Jira

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#142]
### User Story

As a Jira observer 👀 
I want to get issues created in GitHub as Jira tickets
So that I can create reports within Jira that include issues raised on repositories from GitHub.

### Value / Purpose

- Allow teams to reduce copy and pasting information between systems
- Reports 📊
- Comforting data/information 🤗  ingestion 😋  for 😭  Jira
- Did I mention reports?

😮  wow behold the Burn Up report in Jira 🚀 
![Amazing](https://media.giphy.com/media/37Fsl1eFxbhtu/giphy.gif)
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/20583399/166920952-b35127e7-973a-4751-b88d-5ddbf8907ef0.png">

### Useful Contacts

Rachel, Nava, Rich

### Additional Information

Seems GitHub Actions will be able to perform this task
https://github.com/marketplace/actions/jira-issue-creation

Javascript
https://github.com/corda/jira-create-issue-action

The existing Jira integration only seems to do branches, commits, mergers
https://github.com/atlassian/github-for-jira#configure-app

### Definition of Done

- [x] Jira ticket is created when GitHub issue is... created
- [x] Jira ticket is set to Done when GitHub issue is Closed
- [ ] Jira tab is closed forever :wave
- [ ] Documentation has been written / updated
- [ ] Another team member has reviewed

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/cloud-operations/142?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson

**Comment by bagg3rs** [comment]
Ticket created [here](https://dsdmoj.atlassian.net/jira/software/c/projects/TC/boards/740/backlog?issueLimit=100&atlOrigin=eyJpIjoiNmVjMmU5ZjA4NjUwNDJkOWI2NDk1MDY1MTcwZmIzYzQiLCJwIjoiaiJ9)
![image.png](https://images.zenhubusercontent.com/5ee0e1070c1bdefe59b421df/d19c71e9-f0ef-4773-875d-36bdcaf39d22)
Using [Jira Login](https://github.com/atlassian/gajira-login)
And [Jira Create](https://github.com/marketplace/actions/jira-create-issue)
This will create a Ticket.
We can use [Jira Automations](https://www.atlassian.com/software/jira/automation-template-library#/rule-list?systemLabelId=all&page=1&pageSize=20&sortKey=name&sortOrder=ASC) to move ticket based on the status of e.g. Pull Request and Merge.
The alternative is to Open and Close a Ticket based once it's been pulled into `in progress`
Have created an issue #152 to look at an action to prompt for issue on Pull Request to help any automation with code commits.

Outstanding questions
- Which Jira board do we use @rachel

**Comment by bagg3rs** [comment]
Snow ticket added for Jira API KEY
RITM0943440 Created
