### ISSUE TITLE
👩‍💻 Ensure all team members have access to Dev/Prep/Prod DNS/DHCP Portal

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/cloud-operations#191]
### User Story

As a… Cloud Ops Admin
I need/want/expect to… be able to log in to the Dev/Prep/Prod DNS/DHCP Portal
So that… I can do my job

### Value / Purpose

All admins should have the same level of access.

### Additional Information

I don't have access (Gary) so I thought I'd take this opportunity to ensure everyone does. 

### Definition of Done

- [x] Richard Baguley
- [x] Gary Henderson (prod / ~prep~ / ~dev~)
- [x] Aaron Robinson
- [x] Mitch Dawson
- [x] Ky Truong
- [x] Touhidul Islam

**Comment by bagg3rs** [comment]
Removed other team members, and sent a scheduled slack message to ask about Dev/Prep as his account already has access.
