### ISSUE TITLE
☎️ Setup the CloudOps on call rota in PagerDuty

### ISSUE THREAD

**Issue by wanieldilson** [ministryofjustice/cloud-operations#195]
### User Story

As a CloudOps Engineer
I want to know who is on call and when
So that I know where to send out of hours queries out-of-hours

### Value / Purpose

A formal system for our on-call rota

### Useful Contacts

Dan Wilson, Mitch Dawson

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] All team members have logged into PagerDuty

**Comment by NeilRAdams** [comment]
Isn't this already posted here: https://justiceuk.sharepoint.com/sites/TechOpsDepartment/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FTechOpsDepartment%2FShared%20Documents%2FOut%20Of%20Hours%20Support&p=true&ga=1

**Comment by bagg3rs** [comment]
Created issue #232 with outstanding tasks to complete the integration of PagerDuty to AlertManager and Slack.
