### ISSUE TITLE
🕵️‍♀️ Investigate `My Detail - INC1619899 - Slow performance` and create a ⚡️report on findings

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#208]
### User Story

As a Cloud Ops team member
I want to improve the incident process
So that incidents are not bounced unnecessarily around teams.

### Value / Purpose

- INC1619899 has highlighted the fact that the current incident process struggles with the rate of change in the business.
- Neil mentioned in SU that not every alert is an incident.
- Dan mentioned we can use the slackbot as a trigger to the API to raise incidents when it's been declared. 
- Simplify comms by keeping it in channel

### Useful Contacts

Rich B, any ServiceNow user.

### Definition of Done

- [ ] Discussion on findings
- [ ] issues raised from discussion.

**Comment by mitchdawson1982** [comment]
Perform a retro on this to understand why this has been passed around / look for improvement actions in the process. 
Caroline Jones - Incident management (Useful Contact for bouncing incidents)
