### ISSUE TITLE
🚨 Complete PagerDuty integration and configuration

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#232]
### User Story

As a CloudOps Engineer
I expect PagerDuty to be ready for action
So that on-call is automated and alerts are routed to my work mobile when out of hours

### Value / Purpose

🤖 Automate on-call rota
Silence low priority alerts into slack during work hours by moving logic into PagerDuty
Consolidate alert channels in Slack
Allow incidents to be raised in ServiceNow and managed by PagerDuty

### Useful Contacts

Mitch, RB, Dan

- [x]  Request PagerDuty App from Company Portal
- [x]  Create all CloudOps Services in PagerDuty
- [x] All Team members to install PagerDuty App on mobile devices and setup alert preferences.
- [x]  Create [Prometheus integration](https://www.pagerduty.com/docs/guides/prometheus-integration-guide/) with Alert Manager
- [x]  Create Slack channels for PagerDuty alerts 
  - cloud-operations-high-priority-alerts
  - cloud-operations-low-priority-alerts
- [x]  Create rules for PagerDuty > Slack
- [x]  Migrate alerts from Prom AM > Slack to Prom AM > PagerDuty > Slack
- [ ]  Inform channels and archive existing slack channels
- [ ]  Update our docs with new slack channels for our products
- [ ]  Update our onboarding docs for PagerDuty

**Comment by mitchdawson1982** [comment]
Current Progress. We have attached the Pagerduty responder to the DNS DHCP alert configuration and have created two services in Pagerduty (Mojo DHCP & Mojo DNS),  although we are only using the DHCP service currently. We have successfully validated that alerts are received within pager duty and incidents are then created for a critical alert for the DHCP service.

Key Points:
- Services have an integration key which is sent from Prometheus and this is how alerts are mapped to services. You can create something called a global integration which provides the ability to interrogate the incoming alert JSON payload before assigning an alert to a particular service. 
- Our assumptions are that we will will not need to differentiate our support capabilities on a per service basis so it might make sense to have a single "CloudOps" service and use rules to define what happens with each alert.

Service & Event orchestration
We are aiming for a configuration that will receive alerts from Prometheus for all supported services, forward them to slack and or the person on call depending on the time of the day.  
Current
