### ISSUE TITLE
CloudOps Alliance workshop

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#33]
Description
I feel that our alliance principles should be at a higher level, something in the format of the page below. 

https://design-system.service.gov.uk/community/

A 45 minute meeting within the team should be able to bash this out.

https://ministryofjustice.github.io/cloud-operations/documentation/general-information/our-alliance.html#our-alliance

**Comment by Gary-H9** [comment]
First workshop completed on Friday 18th of March. 
[This](https://ministryofjustice.github.io/cloud-operations/documentation/general-information/our-alliance.html#our-alliance) page needs to be updated. 

Next meeting set for Tuesday 29th at 10am.
