### ISSUE TITLE
Enable Secret Scanning on all public repositories

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/cloud-operations#35]
The purpose of this ticket is to ensure secret scanning is enabled on all repositories. 

Example of Secret Scanning: https://github.com/ministryofjustice/staff-infrastructure-monitoring-config/security/secret-scanning

Enable this here: https://github.com/ministryofjustice/staff-infrastructure-monitoring-config/settings/security_analysis

Do this for all repositories within our _domain_.

Update needed on the following Internal/Private
- [ ]  **ministryofjustice/staff-device-private-dns-zone (internal)**
- [ ]  **ministryofjustice/staff-infrastructure-certificate-services (internal)**
- [ ]  **ministryofjustice/staff-infrastructure-metric-aggregation-server (internal)**
- [ ]  **ministryofjustice/staff-infrastructure-metric-aggregator-cloud (internal)**
- [ ]  **ministryofjustice/staff-infrastructure-monitoring-config (internal)**
- [ ]  **ministryofjustice/staff-infrastructure-monitoring-snmpexporter (internal)**
- [ ]  **ministryofjustice/staff-infrastructure-network-services (internal)**
---------------------------
All our repositories
- [ ]  ministryofjustice/cloud-operations (public)
- [ ]  ministryofjustice/cloud-operations-slack-bot (public)
- [ ]  ministryofjustice/network-access-control-admin (public)
- [ ]  ministryofjustice/network-access-control-disaster-recovery (public)
- [ ]  ministryofjustice/network-access-control-infrastructure (public)
- [ ]  ministryofjustice/network-access-control-integration-tests (public)
- [ ]  ministryofjustice/network-access-control-server (public)
- [ ]  ministryofjustice/staff-device-dhcp-server (public)
- [ ]  ministryofjustice/staff-device-dns-dhcp-admin (public)
- [ ]  ministryofjustice/staff-device-dns-dhcp-infrastructure (public)
- [ ]  ministryofjustice/staff-device-dns-server (public)
- [ ]  ministryofjustice/staff-device-docker-base-images (public)
- [ ]  ministryofjustice/staff-device-logging-infrastructure (public)
- [ ]  ministryofjustice/staff-device-logging-syslog-to-cloudwatch (public)
- [ ]  **ministryofjustice/staff-device-private-dns-zone (internal)**
- [ ]  ministryofjustice/staff-device-shared-services-infrastructure (public)
- [ ]  **ministryofjustice/staff-infrastructure-certificate-services (internal)**
- [ ]  **ministryofjustice/staff-infrastructure-metric-aggregation-server (internal)**
- [ ]  **ministryofjustice/staff-infrastructure-metric-aggregator-cloud (internal)**
- [ ]  ministryofjustice/staff-infrastructure-monitoring (public)
- [ ]  ministryofjustice/staff-infrastructure-monitoring-app-reachability (public)
- [ ]  ministryofjustice/staff-infrastructure-monitoring-blackbox-exporter (public)
- [ ]  **ministryofjustice/staff-infrastructure-monitoring-config (internal)**
- [ ]  ministryofjustice/staff-infrastructure-monitoring-deployments (public)
- [ ]  **ministryofjustice/staff-infrastructure-monitoring-snmpexporter (internal)**
- [ ]  **ministryofjustice/staff-infrastructure-network-services (internal)**
- [ ]  ministryofjustice/staff-infrastructure-smtp-relay-server (public)

**Comment by bagg3rs** [comment]
Discussed with GitHub Org owners. 
If repo is public, secret scanning is enabled by default by GitHub
[Private](https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning#:~:text=on%20public%20repositories.-,Note%3A,-Organizations%20using%20GitHub) repo's need a license which we can request for from ops engineering.

**Comment by jakemulley** [comment]
Hello!

As discussed with @bagg3rs, these repositories now have GitHub Advanced Security licenses:

- [x]  ministryofjustice/staff-device-private-dns-zone (internal)
- [x]  ministryofjustice/staff-infrastructure-certificate-services (internal)
- [x]  ministryofjustice/staff-infrastructure-metric-aggregation-server (internal)
- [x]  ministryofjustice/staff-infrastructure-metric-aggregator-cloud (internal)
- [x]  ministryofjustice/staff-infrastructure-monitoring-config (internal)
- [x]  ministryofjustice/staff-infrastructure-monitoring-snmpexporter (internal)
- [x]  ministryofjustice/staff-infrastructure-network-services (internal)

Public repositories don't need GitHub Advanced Security licenses and will already be enabled. It may be preferable to enable "Push protection" to block commits that contain secrets. You can do that via Settings -> Security Analysis.

It'd be preferable for this repositories to be made public to meet point 12 of GOV.UK's Service Standard - [12. Make new source code open](https://www.gov.uk/service-manual/service-standard/point-12-make-new-source-code-open).

Any issues, do reach out.
