### ISSUE TITLE
🕵️  AWS Security - SSO via GitHub/Auth0 for AWS Accounts

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#39]
The Modernisation platform that maintains the AWS Root account for MoJ enables SSO with GitHub on new AWS  accounts. We can make use of this solution to enable AWS via GitHub group membership.SSO information  Requirements- Create required groups within GitHub (further ticket to define as code) - Assign these users to groups to AWS accounts- Where users are not part of MoJ GitHub org we should look to add to GH Org or define their IAM via Code e.g. BSI Pen Testers?- Clean up all accounts local IAM accounts Shared Services, Prod, Prep, Dev, PKI Prep/Prod, and Dev. - Update documentation where needed e.g. new starter guides.

DoD

GitHub Groups/Roles defined and users can log onto MoJO AWS accounts via SSO.IAM accounts removed from AWS Accounts our MojO accounts Shared, Dev, Prep, Prod, PKI Prep/Prod, PKI Dev.

**Comment by Gary-H9** [comment]
Completed @kyphutruong removed relevant individual account from PKI accounts today.
