### ISSUE TITLE
Review CICA's AWS accounts

### ISSUE THREAD

**Issue by ermiasworku** [ministryofjustice/cloud-operations#42]
User Story: As a cloud ops engineer, I have access to the CICA AWS environment and an understanding of applications & services used by the organisation. 

## Value / Purpose 
To support applications and services used by the organisation.

## Additional Info 
All required permission will be provided by the CICA team who currently work in the Cloud Ops team and access will be granted from MoJ devices.

**Definition of Done.**

1. Access to Dev, UAT and Prod environment from MoJ Devices.
2. I  have an understanding and high-level list of all applications and services hosted in AWS.

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/cloud-operations/42?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson
