### ISSUE TITLE
🏷️ Apply consistent labels across our repositories

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#44]
## User Story

As a CloudOps engineer
I want to have consistent labels across my repositories
So that I can easily identify and filter tickets on the board

## Value / Purpose

Consistency across repositories with regards to labels which means we can filter based on e.g. `security`

## Additional Information

- [Creating the Same Label set in Multiple Repos at Once](https://help.zenhub.com/support/solutions/articles/43000185124-create-the-same-label-set-in-multiple-repos-at-once)
- [Labels including emoj's 🔥 ](https://help.zenhub.com/support/solutions/articles/43000480398-creating-github-issue-labels) 

## Definition of Done (DoD)

- Label set defined
- Labels applied across our[ repos](https://github.com/ministryofjustice/cloud-operations#core-repositories)

Checklist for definition of done and acceptance criteria, example below (optional).

Example

- [x] Documentation has been written / updated  
- [x] README has been updated  
- [x] User docs have been updated  
- [x] Another team member has reviewed  

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by Gary-H9** [comment]
Potential labels 'monitoring' and 'alerting'.

**Comment by bagg3rs** [comment]
Service or application labels are defined here
https://github.com/ministryofjustice/technology-operations#tags-for-application-and-services

**Comment by bagg3rs** [comment]
Used the issue `Issue to add labels` to apply across all repo's can be used to add additional labels in the future with these instructions https://help.zenhub.com/support/solutions/articles/43000185124-create-the-same-label-set-in-multiple-repos-at-once
