### ISSUE TITLE
🏷️ Add GitHub Actions labeler

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#46]
## User Story

As a CloudOps Engineer
I expect my GitHub pull requests and issues to be automatically labeled 😎
So Issues/PRs can be filtered based on labels e.g. service, ad-hoc

## Value / Purpose

Filtering and beautifying Pull requests :heart:

## Additional Information
ticket #44 is a prerequisite 
https://github.com/actions/labeler
[example](https://github.com/ministryofjustice/modernisation-platform/blob/main/.github/labeler.yml) on mod platform repo 

## Definition of Done (DoD)

GitHub action added to all our repo's

Checklist for definition of done and acceptance criteria, example below (optional).

Example

- [ ] Documentation has been written / updated  
- [ ] README has been updated  
- [ ] Another team member has reviewed  

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/cloud-operations/46?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson

**Comment by bagg3rs** [comment]
labels applied succuessfully
![image.png](https://images.zenhubusercontent.com/5ee0e1070c1bdefe59b421df/21a7e377-d924-4b48-877c-4b652789b60c)

**Comment by bagg3rs** [comment]
Have added issues to this ticket
![image.png](https://images.zenhubusercontent.com/5ee0e1070c1bdefe59b421df/b885271f-fb16-4f69-9613-95e9ed2e019c)

**Comment by bagg3rs** [comment]
Example [pull request](https://github.com/ministryofjustice/staff-infrastructure-certificate-services/pull/22) with issue and pr labeled

**Comment by bagg3rs** [comment]
https://github.com/ministryofjustice/cloud-operations/pull/138
https://github.com/ministryofjustice/staff-device-shared-services-infrastructure/pull/34
https://github.com/ministryofjustice/staff-device-dns-dhcp-infrastructure/pull/186
https://github.com/ministryofjustice/staff-device-dns-dhcp-admin/pull/495
https://github.com/ministryofjustice/staff-device-dhcp-server/pull/175
https://github.com/ministryofjustice/staff-device-dns-server/pull/109
https://github.com/ministryofjustice/staff-device-private-dns-zone/pull/17
https://github.com/ministryofjustice/staff-infrastructure-metric-aggregation-server/pull/24
https://github.com/ministryofjustice/staff-infrastructure-monitoring-snmpexporter/pull/10
https://github.com/ministryofjustice/staff-infrastructure-monitoring-dns-reachability/pull/2
https://github.com/ministryofjustice/staff-infrastructure-smtp-relay-server/pull/24

**Comment by ASTRobinson** [comment]
https://github.com/ministryofjustice/staff-infrastructure-monitoring-deployments/pull/105
https://github.com/ministryofjustice/staff-infrastructure-monitoring-config/pull/249

**Comment by bagg3rs** [comment]
Pull requests merged
