### ISSUE TITLE
Add Github MoJ GitHub standards badge

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/cloud-operations#64]
## User Story

As a CloudOps Engineer
I want to have visual guidance on the status of my repos
So that I get visual feedback on status of MoJ GH standards

## Value / Purpose

Repository badge for our repositories that will display if meets the [MoJ github repository standards](https://github.com/ministryofjustice/github-repository-standards).

![image](https://user-images.githubusercontent.com/20583399/161419039-d6b44e1e-d000-47b8-b202-95f047427b16.png)

## Additional Information

Instructions from Operations Engineering about adding badge [here](https://operations-engineering.service.justice.gov.uk/documentation/runbooks/add-repo-badge.html#badge-code) 

https://github.com/ministryofjustice/operations-engineering/issues/642

## Definition of Done (DoD)

All repo's have badges
- [X]  staff-device-dns-dhcp-admin
- [ ]  staff-device-docker-base-images (Repository is now archived)
- [x]  staff-device-logging-infrastructure
- [x]  staff-device-shared-services-infrastructure
- [ ]  staff-infrastructure-monitoring (This repository has been archived)
- [x]  staff-infrastructure-monitoring-blackbox-exporter
- [ ]  staff-infrastructure-monitoring-deployments (This repository has been archived)
- [x]  staff-infrastructure-smtp-relay-server
- [x]  network-access-control-admin
- [x]  network-access... repos

Checklist for definition of done and acceptance criteria, example below (optional).

Example

- [ ] Documentation has been written / updated  
- [ ] Another team member has reviewed  
- [ ] Tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by bagg3rs** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/cloud-operations/64?planning-poker) with ZenHub @ASTRobinson @Gary-H9 @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson

**Comment by ASTRobinson** [comment]
all public NVVS DevOps repos have now had the moj compliance badge added.
