### ISSUE TITLE
🕵️‍♂️ Issue 1 

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/cloud-operations#67]
Please see below; row 1:

https://docs.google.com/spreadsheets/d/1eZH6v34UQoO2SRcoDcFw5MlFccvIgOnu1Y_HTGuPKD4/edit#gid=0

**Comment by Gary-H9** [comment]
@bagg3rs will gather some more information on this. 🙏

**Comment by Gary-H9** [comment]
@bagg3rs will gather some more information on this. 🙏

**Comment by wanieldilson** [comment]
Richard to confirm with @jakemulley if this is a problem.

**Comment by bagg3rs** [comment]
To be completed in issue https://github.com/ministryofjustice/cloud-operations/issues/93
