### ISSUE TITLE
🕵️‍♂️ Issue 3

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/cloud-operations#76]
Please see row 3 in the sheet below: 

https://docs.google.com/spreadsheets/d/1eZH6v34UQoO2SRcoDcFw5MlFccvIgOnu1Y_HTGuPKD4/edit#gid=0

**Comment by wanieldilson** [comment]
https://github.com/ministryofjustice/staff-device-logging-infrastructure/pull/49

**Comment by wanieldilson** [comment]
Logging VPC is fixed, do we want to lock down the default VPC manually?

**Comment by wanieldilson** [comment]
Decided against messing with the default VPC - This issue is fixed!
